runtime: nodejs22
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6
network: {}
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
